#!/bin/bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
SHORTCUT_DIR="${1:-$HOME/Desktop}"

for script in start-dell-display.sh stop-dell-display.sh; do
  if [[ ! -f "$APP_DIR/$script" ]]; then
    echo "缺少 $script。请在完整的 dell-display 项目文件夹内运行安装工具。" >&2
    exit 1
  fi
done

mkdir -p "$SHORTCUT_DIR"
write_shortcut() {
  local name="$1" script="$2"
  # Quote the installed project path so spaces and shell characters remain literal.
  printf '#!/bin/bash\n# Generated by dell-display/install-desktop-shortcuts.sh\nSCRIPT=%q\nif [[ ! -f "$SCRIPT" ]]; then\n  echo "项目文件夹已移动，请重新运行安装桌面快捷方式.command。" >&2\n  exit 1\nfi\nexec /bin/bash "$SCRIPT"\n' "$APP_DIR/$script" > "$SHORTCUT_DIR/$name"
  chmod +x "$SHORTCUT_DIR/$name"
}

write_shortcut '连接 Dell 扩展屏.command' start-dell-display.sh
write_shortcut '断开 Dell 扩展屏.command' stop-dell-display.sh
echo "已安装连接、断开两个桌面快捷方式：$SHORTCUT_DIR"
